# Generated by Django 6.0.5 on 2026-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Votre nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (optionnel)')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du problème')),
                ('categorie', models.CharField(choices=[('commerce', 'Commerce & Affaires'), ('agriculture', 'Agriculture'), ('sante', 'Santé'), ('education', 'Éducation'), ('transport', 'Transport'), ('finance', 'Finance'), ('logement', 'Logement'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description du problème')),
                ('solution_souhaitee', models.TextField(verbose_name='Solution souhaitée')),
                ('condition', models.CharField(choices=[('urgent', "Urgent – Besoin d'aide immédiate"), ('court_terme', 'Court terme – Dans les prochaines semaines'), ('long_terme', 'Long terme – Pas de pression immédiate'), ('information', 'Information seulement – Juste partager')], default='information', max_length=50, verbose_name='Urgence / Condition')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Problème',
                'verbose_name_plural': 'Problèmes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
